# Generated by Django 3.2.8 on 2021-10-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='books/'),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='image',
            field=models.ImageField(upload_to='dalle/'),
        ),
    ]
