# Generated by Django 3.2.8 on 2021-10-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_alter_book_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='image',
            field=models.TextField(),
        ),
    ]
